[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "clusview"
dynamic = ["version"]

dependencies = [
  "bertopic",
  "tqdm",
  "black",
  "isort"
]

[tool.hatch.version]
raw-options = { root = "../.." }
source = "vcs"
